sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: BbZh+WSJ0t8WPYLdP+y8LV4+34A+6S2pbNiGehORGkmMr71oy9DDiSN13qcKko3MQ4Ag+A6PlcqcdA2X4nlRVa4C43U9vv0slBfmu2SBV0ErTLRYFUHFJE5nd+vA85dPnIUJ/aBJ0tIPUhGi15rju+Im4g1IzgJ8FChVq5G0Cx4pQ+p8y+EUXLXx58ljb0ategGUSGhdXkG70YWg1K/jOwFYUuWCJ5D5S/U/PRueNqGMOizMN9PWP35zDHNJ07VM44hLAcq74VcTIjPMZeU5qGsh5yFeRNplyMsJ8LS/tVSI2Vq5H7V+eO4MPcJNJzXEt/AnBuqBDojbfqIIWcQ3WZwTqhJpU9S9RElqa9dL3k6C4VBIKg/NJD3RtZfIuYqyIgycvNPIiweA5/hOiXM9HH0mihEOUDBXjH+AutDV5OUzCewtlBQvaEHDdFh9OD8aPFWrWbFEo94oJefXIqvJeS0fQYld9tr8F9jnDlEWiBFfA0F70xyj0BrhcbTGjno0cyJUEGWV3IlgntLYY4MxC0Osz/VS/W5ieFKHXRbpkDiK7KkMD65K2qbTSsP9BF6kDW577M5QhSjamEs9AuojqaLWtuhehO3iodDhnMFPN4B13gaXM7ylVBnRcVaWe8LxOywM6T+RFVrE1aFN64YmPNoxZplQ4qKlgKl+EhWsS0o=
branches:
  only:
  - master
