sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: osGz2axy7oljsxUDm9yP6bQqUO0z70SmgKq4VouZLBX7qHmthdQW2hEltKPhHLEkZbH5TQEtcfIaGHnpF4XTuy//jpnHJlfqw4QY7i6c8QPJXQEZXWHRTQjvEDMF8/YQ3YtCQq345XvuRCUPZ4JO4Rt9HfR1Ewkj/fBid7dKTjGU3Ju+r+LGVAZtmOSRKEq8JdkAiXgY6SAvVM1vZnLHiZX0BzcVVVqN/HlUnUpTVX8Uo2ouyor6isEZZvsB2h+qHbPuQ0V9bU9Mgu47rR9PFSpvj8Jn1g+HzbMvrT5ei/hT1gZVsrnrYXdqZXGO9CngPFWkMkJVrqqsduFh2gUse7SUDWXTBKNEsv2rizeB6bKu2avV2y3ZqL//J0Xo9G+Msu/zGRK3j5/cxLXpnCCxUjTQz+c1Z4Aq5Ew/skV/BEUtrsZG3KkGugtaiQD1+lnK65Fu+7Mxn0IV33jZa1UCldlTwUk9I1s7t4+g+eLXNHkwlijUPBYAt+CQAiLsRvt6zssLDsd6fSaF3WrkDpyeUW9hlCLy8MlXzQ7Su1d7AbyQgnTw7uF3NiwZJu8kd5JkMB3gwEnym+qukzZ3eyczCHJ5JN4XE545tsjjqkCq5w/kpZbLrJgBTpWhRsGc+DKqodqmE1ufpJqmhaIFD2eTjzwOZ3cEI9Jx+0Ma20e7KJQ=
branches:
  only:
  - master
