sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
before_script:
  - git config --global user.email "travis.r.valdez@gmail.com"
  - git config --global user.name "Travis-CI"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: TcPGrY3NQ+wVAtX1/CO3xRzQJ2fWacGtNUBQwwFFoFranJChkJsF9N3aZtO0VuwsA8WT+MWIf+8Eh4ZnVVTtjV1mZHb4qU94f+YDOvVfV7GkxvURfwRrNDGrMwARjJQ1xAc7HlAOXY2x1OgSVba78AzgA7+ej2mnfYOyIGfNj6svta+1PfThMRxO2p74cfulJ4YeI/zAOVAo+3fohWIcj7fSd7msRRUMtcEx7rXb9fs0yy9qRHzhCnCFz7/Anooo8DCpMTcw0XrXV2GlteAeD9iUXjFx86Q2mFbjQZBy8dJ4zQm+QU0jRMkKbPkVZZ2+McaCEUBhPryUwoEELSTC+bpHbl//FO1LIrfG9QS9Gs4r7tAPvTpBix+PTsW+CDcO1XRGJgB59ZJTIoJhJwN0c8hvlSS9sgENqYqUq4JGCEwbMx1LdGi6uUaNjf6cuMq+bQcyfEhw6Oas3Ez+tn2xpUukbEkZwk/DMT2t+hl41kHMdpQ2ArWACfosLsDL7Yyd647GAhn/eq4Ji1tERtWLzRCbSnrX7AaAVr4rLznNEHrGUBY5sfd0GBavABA7jIVuqMLWT8VK9Mx6x9P2PEHeT0VxvvIgjrtYp3mLSfrtfRQ/gHEDM6HithQ6nX5aNL0KzrF2ONa90uqJGi55Bshuv+KqnBPMVqxyBN2b7mu0irs=
branches:
  only:
  - master
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt release
