sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
before_script:
- git config --global user.email "travis.r.valdez@gmail.com"
- git config --global user.name "Travis-CI"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: gy755fdYZjKWk1CvbZNyDLmHPbww3WFegmjzkpc1TTOX3aKdPAypsD8iqRdjROZrbhyZtX6XmlwykdtrSS5elAQ4hxrbLKUMnTvMAYxu/SNPmIOA/GeeZ0SmNRFhlGzViFAibIn/v/klCXcUnpmgWQTNYXAlww2dtJQqF85QRXA0Q1uSoqfhXGU66yLXCpEDM3SS1OfuIRggbErAQQmY4xsrmdQf4PMVIxbcptBXhJFs98Zx0RfcN5un8e6vAj9FgaKzyUdKAXvuQ7hDLansGlRDuXhn7OiulZT48dOen5LVPVd8DZjGSH4UT9LCrCykvx4dA5e2tzI9LeatnwIxKZiTJSCnSxidEFXlu3+zhG8gWo+LnRGzTL6dPkHtZ9VEJQeuxqn8YLeW+JagAxponhaBljGQ7W06qem0kdsLS7TlBUO/7OHlzX6UN6rYzZVfMkjKkuxtStvDbzIXB7xDfCuDojvtMQMu++yI3Wp/OJzAFwYRYeKYd97bCv5Jsqi8bfRzvJcaEkHWmHem2iEGGbgJaZUT7HEESzi1vKowcP5i+xHLnNo0OQ583TULoMT6AdSXSwXKiGYFIYJG0zoqdEcLFUncqLF/24D7laTt3kq+lnyqUbhVNvdZk8QPjk4RIoYcHGvbc/JFpXS6SyWLeOCnUUYvBXyzNOlOqi6GIVs=
branches:
  only:
  - master
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
