sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: hGpEWbQXMoZDTKAyG4AEKT/Q8CzjJ7TAT4ZDKDmYsIeDjw9IYLVpG9dMArpguHP9eHzcZn1sX/WTWLm8d1fdBGZgUXcKOXb1b8SFKd/A9SNJhIAYlpW9xde6LgUpbOywFfbH93+vkXGiHTxbvdf5ESRrYD8wGGgTKSUAv7/2IPaA9Ea3JX2XMT0v4MIAIndat5SDrcjgLasHev7P8hQo8k4Rjx94axbJUHKImDPl+sAwCtrD3kWikAGwcrnBNoaYw8QBj6tG3XH4RbAbSu4U5GKABOBJNbSq5R9W7jdvTY81oxH/PWTOeIeQBQQk+ekRrtb/GTdVBrLVuevs++63EW5OEARZJCpLLliD/NszhuxNHh7PgNJvO4rLjnxZk3b/QbjbNXzsACFKI0WU0PEaYeGxNB+2oVRuMyw4gtO7DVcCTO1ZC/zsO/DOoajzbsenpn76PR0JykeNcu8u3YvNG2sD9NoUFAtw9bzJK1/PaYNhOL1sF9EUBVqUE9aZYGbp1nqLuhgsBdF5YwzZ2yGX2bKIUnVMvyLnUiZMN1Sr/siglUqsmXRvtQPD/GAVrgr74DvfWcuXk6TnLl4csHtK61abSGJwsBwlvdovq/Rrrm4wfqXqJ801l3+EGUXJtaOO+ghDw4M5aTo3Qwcsf9gkwj9kZE+eljxTL7irxwxmlWU=
  - secure: TcPGrY3NQ+wVAtX1/CO3xRzQJ2fWacGtNUBQwwFFoFranJChkJsF9N3aZtO0VuwsA8WT+MWIf+8Eh4ZnVVTtjV1mZHb4qU94f+YDOvVfV7GkxvURfwRrNDGrMwARjJQ1xAc7HlAOXY2x1OgSVba78AzgA7+ej2mnfYOyIGfNj6svta+1PfThMRxO2p74cfulJ4YeI/zAOVAo+3fohWIcj7fSd7msRRUMtcEx7rXb9fs0yy9qRHzhCnCFz7/Anooo8DCpMTcw0XrXV2GlteAeD9iUXjFx86Q2mFbjQZBy8dJ4zQm+QU0jRMkKbPkVZZ2+McaCEUBhPryUwoEELSTC+bpHbl//FO1LIrfG9QS9Gs4r7tAPvTpBix+PTsW+CDcO1XRGJgB59ZJTIoJhJwN0c8hvlSS9sgENqYqUq4JGCEwbMx1LdGi6uUaNjf6cuMq+bQcyfEhw6Oas3Ez+tn2xpUukbEkZwk/DMT2t+hl41kHMdpQ2ArWACfosLsDL7Yyd647GAhn/eq4Ji1tERtWLzRCbSnrX7AaAVr4rLznNEHrGUBY5sfd0GBavABA7jIVuqMLWT8VK9Mx6x9P2PEHeT0VxvvIgjrtYp3mLSfrtfRQ/gHEDM6HithQ6nX5aNL0KzrF2ONa90uqJGi55Bshuv+KqnBPMVqxyBN2b7mu0irs=
branches:
  only:
  - master
