sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: UTFeWXk73jOXrWmyTZZWHafvjRT3pqpxb/nIdN4JQgrrVgnif42lh/Mmd39Jpf4HwemkZ3tU3E3TLJCr9aTJag6yFyLAj/i0/BbhHV7QOy/QzULN/ayif5qTJz093Xm5lwz9wGxuG1pDVj8Ybroga9U5/mrKJr1x/younK4J+YOV/VlfdbrsZ/ncBJNq1kWXKqZ7Vs7Zhv4NxxONZJ6KdCR3yBoM7B5KYVLjEj1kVvuD3cqFm7f2zgDdtxPxAFaqQ6egaVZr/ScBeVUYvW81/j/JlkVg4otPlyNXXvDOyqgUywsq3xoPe5rq53h7pH5NNxzsdRj+VbEfGl50pnN+gV9zKRXmiv1nLxCIPavFCyFDSe5Ahzm+u5UR1lac7ogLaLL5oaVXur3dsJQ3pC3lAB920JYXeLUeHGCuoTTM6seNNmb8WWw4uXdhR6a173XHeJNXwnXqKy0CUBZjnSNZHkp2h51vxG8wowLazqMWi9BLQHFXH+yvdFrtDJwj801lHWsrjC/XyEbnuNqQhk03ZdhDnjzjZ9PnwrGEjV5O1HQA/SS2j+HX22nDfOAiSoJuki9bQiWL+T0pQ5ZDEqOWB0oqQolAkgYctGtYfTnY6zBeqPI2dE5UWEiJoyw7i/qpRSYN7mnf9Y+7skFqtMOKHxp1GLKptNIPISEUKgbnYyc=
branches:
  only:
  - master
